### ISSUE TITLE
Notifications Failing For macOS 13 beta

### ISSUE THREAD

**Issue by Kief5555** [teaminkling/now-playing#110]
### What happened?

No notifications are showing despite having the correct permissions and toggled.

### Extra context?

13.0 Beta (22A5266r)

### Do you accept the Code of Conduct?

- [X] I agree to follow Inkling Interactive's Code of Conduct.

**Comment by paced** [comment]
Thank you for the report @Kief5555. As this is the main feature of Now Playing, I'll be taking a look at this bug immediately.

**Comment by paced** [comment]
Notifications are not failing for 12.3.1 (Monterey) and therefore we cannot prioritise this ticket. This is more than likely a dependency problem with `node-notifier`.

In the latest minor release, it is possible these issues may be resolved. If it's okay, I'll ping you when v0.11.0 is out if you would like to test and report back here to close it.

**Comment by Kief5555** [comment]
Seems like I fixed it. 
First, you have to allow control permissions. Then you have to go into system prefs and enable notifications for _spotify_ and not the Now Playing application. Then a restart is required for some dumb reason.

**Comment by Kief5555** [comment]
The enable notifications button does nothing. It says it's checked but in reality a user has to do all the work. 

As I am a node developer I can open a bug report for the package if you like.

**Comment by paced** [comment]
The prompt for permissions appears for `terminal-notifier` or the Spotify application when the first notification occurs. This may be seen as a UX bug, but does not indicate regression of existing notifications behaviour.

Additional permissions other than notifications was not found in testing for Monterey, and changing notifications settings for an application did not require an app or system update.

I ask that we leave this issue standing for a while as Apple fixes bugs in Ventura and as my team prioritises other stability improvements. Closing for now.

**Comment by Kief5555** [comment]
Ok.
