### ISSUE TITLE
Just Notifications

### ISSUE THREAD

**Issue by GrandWasTaken** [teaminkling/now-playing#80]
Would really love a version of the app where its just for notifications.

**Comment by paced** [comment]
@GrandWasTaken That's not a bad idea, but I should note a few limitations with this:

- There would not be any significant improvement in battery life, performance, or resource utilisation.
- The file size of the application would remain the same as well.

The miniplayer is not a big part of the performance of the app. Even if it never is rendered, it won't be any "lighter" for two reasons: the Electron framework as it currently is, and the Spotify API needs to be polled once every five seconds. There are [no workarounds to avoid doing this](https://community.spotify.com/t5/Spotify-for-Developers/Access-to-websockets/td-p/4955299) until Spotify changes their API.

However, I could make it that left-clicking the tray icon opens the right-click menu if that option is enabled. Does that sound good? It'd essentially be the same as using something like Bartender or Vanilla to hide tray icons.

**Comment by GrandWasTaken** [comment]
I see. Was hoping that could safe more energy without the mini player. If that's the case than there's no need to make a separate version I guess.

**Comment by paced** [comment]
Yeah, sorry about that. It's up to Spotify. You might get marginally better battery economy with App Store apps that cycle every 10 seconds (or more) instead of 5, but you'll also notice a delay in notifications. Otherwise, all apps will probably use the same amount of battery.

**Comment by flammable** [comment]
Sorry to post in a closed GitHub issue, but I'd love a notification-only version of this app. That's how I used the old "Spotify Notifications" app (and where I found this one -- thanks!). If I needed to change any settings, I'd like double-click the application and it'd bring up the preferences window.

I just got one of the fancy new MacBook Pros with a notch, and I'm suddenly more aware of my menu bar real estate. Anything to trim that down would be welcome. Thanks!

**Comment by paced** [comment]
The issue with that is that it's a significant departure from the way the app currently works and, in my opinion, would be difficult for new users to understand. Either options must appear in the tray or in the dock, and putting it in the dock doesn't quite make sense to me.

May I suggest using [Vanilla](https://matthewpalmer.net/vanilla/)?

**Comment by flammable** [comment]
Thanks! I agree it's not a good fit for the dock.

Actually, I've been meaning to try Bartender, so I finally installed it - that works great. I'll keep Vanilla around in case Bartender stops working at some point.

I really appreciate the app and the assistance, thanks!
