### ISSUE TITLE
How do i like a song?

### ISSUE THREAD

**Issue by msudgh** [teaminkling/now-playing#88]
Hi @teaminkling, its really good looking app and written clean. It would be nice to draw a like/heart button on main window.

**Comment by paced** [comment]
Hi @msudgh, thanks for the patience. You can like a song with the `+` button at the bottom right of the mini-player. Clicking on "Save to Your Library" should be the same as liking the song.

**Comment by msudgh** [comment]
@paced Thanks for respond
